job "counting-dashboard" {
  # Deploy to dc1 datacenter (adjust as needed)
  datacenters = ["dc1"]
  
  type = "service"

  # Multi-architecture support (AMD64 and ARM64)
  constraint {
    operator = "regexp"
    attribute = "${attr.cpu.arch}"
    value     = "amd64|arm64"
  }

  # Counting service group (backend)
  group "counting-service" {
    # Single instance for development, increase for production
    count = 1

    # Network configuration
    network {
      mode = "host"
      
      port "http" {
        # Static port for easier access
        static = 9001
        to     = 9001
      }
    }

    # Register service with Nomad native service discovery
    service {
      provider = "nomad"
      name = "counting-service"
      port = "http"

      # Service metadata
      meta {
        version     = "1.0.0"
        environment = "development"
      }

      # Health check
      check {
        type     = "http"
        path     = "/health"
        interval = "10s"
        timeout  = "2s"
        
        check_restart {
          limit           = 3
          grace           = "10s"
          ignore_warnings = false
        }
      }
    }

    # Counting service task
    task "counting-service" {
      driver = "docker"

      config {
        image = "aimeeu/counting-service:latest"
        ports = ["http"]
        
        # For local development with local image
        # Build: docker build -t counting-service:latest ./counting-service
        force_pull = false
      }

      # Environment variables
      env {
        PORT = "9001"
      }

      # Resource allocation
      resources {
        cpu    = 500  # MHz
        memory = 256  # MB
      }

      # Logging
      logs {
        max_files     = 5
        max_file_size = 10
      }
    }

    # Restart policy
    restart {
      attempts = 2
      delay    = "15s"
      interval = "5m"
      mode     = "fail"
    }
  }

  # Dashboard service group (frontend)
  group "dashboard-service" {
    # Single instance for development, increase for production
    count = 1

    # Network configuration
    network {
      mode = "host"
      
      port "http" {
        # Static port for easier access
        static = 8080
        to     = 8080
      }
    }

    # Register service with Nomad native service discovery
    service {
      provider = "nomad"
      name = "dashboard-service"
      port = "http"

      # Service metadata
      meta {
        version     = "1.0.0"
        environment = "development"
      }

      # Health check
      check {
        type     = "http"
        path     = "/health"
        interval = "10s"
        timeout  = "2s"
        
        check_restart {
          limit           = 3
          grace           = "10s"
          ignore_warnings = false
        }
      }
    }

    # Dashboard service task
    task "dashboard-service" {
      driver = "docker"

      config {
        image = "aimeeu/dashboard-service:latest"
        ports = ["http"]
        
        # Mount the config file into the container
        volumes = [
          "local/config.js:/usr/share/nginx/html/config.js"
        ]
        
        # For local development with local image
        # Build: docker build -t dashboard-service:latest ./dashboard-service
        force_pull = false
      }

      # Template to inject counting service URL using Nomad service discovery
      template {
        data = <<EOH
// Counting Service Configuration
// Generated by Nomad template at runtime
window.COUNTING_SERVICE_URL = '{{ range nomadService "counting-service" }}http://{{ .Address }}:{{ .Port }}{{ end }}{{ if not (nomadService "counting-service") }}http://192.168.64.27:9001{{ end }}';
console.log('Counting Service URL configured:', window.COUNTING_SERVICE_URL);
EOH
        destination = "local/config.js"
        change_mode = "restart"
      }

      # Environment variables
      env {
        NGINX_PORT = "8080"
      }

      # Resource allocation
      resources {
        cpu    = 300  # MHz
        memory = 128  # MB
      }

      # Logging
      logs {
        max_files     = 5
        max_file_size = 10
      }
    }

    # Restart policy
    restart {
      attempts = 2
      delay    = "15s"
      interval = "5m"
      mode     = "fail"
    }
  }
}