job "counting-dashboard-consul-dns" {
  # Deploy to dc1 datacenter (adjust as needed)
  datacenters = ["dc1"]
  
  type = "service"

  # Multi-architecture support (AMD64 and ARM64)
  constraint {
    operator = "regexp"
    attribute = "${attr.cpu.arch}"
    value     = "amd64|arm64"
  }

  # Counting service group (backend)
  group "counting-service" {
    # Single instance for development, increase for production
    count = 1

    # Network configuration
    network {
      port "http" {
        to = 9001
      }
    }

    # Register service with Consul for DNS discovery
    service {
      name = "counting-service"
      port = "http"
      
      tags = [
        "counting",
        "backend",
        "go",
        "version-1.0"
      ]

      # Service metadata
      meta {
        version     = "1.0.0"
        environment = "development"
      }

      # Health check
      check {
        type     = "http"
        path     = "/health"
        interval = "10s"
        timeout  = "2s"
      }
    }

    # Counting service task
    task "counting-service" {
      driver = "docker"

      config {
        image = "aimeeu/counting-service:latest"
        ports = ["http"]
        
        # For local development with local image
        # Build: docker build -t counting-service:latest ./counting-service
        force_pull = false
      }

      # Environment variables
      env {
        PORT = "${NOMAD_PORT_http}"
      }

      # Resource allocation
      resources {
        cpu    = 500  # MHz
        memory = 256  # MB
      }

      # Logging
      logs {
        max_files     = 5
        max_file_size = 10
      }
    }

    # Restart policy
    restart {
      attempts = 3
      delay    = "15s"
      interval = "5m"
      mode     = "fail"
    }

    # Update strategy
    update {
      max_parallel     = 1
      min_healthy_time = "10s"
      healthy_deadline = "3m"
      auto_revert      = true
    }
  }

  # Dashboard service group (frontend)
  group "dashboard-service" {
    # Single instance for development, increase for production
    count = 1

    # Network configuration
    network {
      port "http" {
        static = 8080
        to     = 8080
      }
    }

    # Register service with Consul for DNS discovery
    service {
      name = "dashboard-service"
      port = "http"
      
      tags = [
        "dashboard",
        "frontend",
        "nginx",
        "version-1.0"
      ]

      # Service metadata
      meta {
        version     = "1.0.0"
        environment = "development"
      }

      # Health check
      check {
        type     = "http"
        path     = "/health"
        interval = "10s"
        timeout  = "2s"
      }
    }

    # Dashboard service task
    task "dashboard-service" {
      driver = "docker"

      config {
        image = "aimeeu/dashboard-service:latest"
        ports = ["http"]
        
        # DNS configuration to use Consul DNS
        # This allows the dashboard to resolve counting-service.service.consul
        dns_servers = ["${attr.unique.network.ip-address}"]
        dns_search_domains = ["service.consul"]
        
        # Mount the config file into the container
        volumes = [
          "local/config.js:/usr/share/nginx/html/config.js"
        ]
        
        # For local development with local image
        # Build: docker build -t dashboard-service:latest ./dashboard-service
        force_pull = false
      }

      # Template to inject counting service URL using Consul DNS
      template {
        data = <<EOH
// Counting Service Configuration
// Generated by Nomad template using Consul DNS at runtime
window.COUNTING_SERVICE_URL = '{{ range service "counting-service" }}{{ if .Status | eq "passing" }}http://counting-service.service.consul:{{ .Port }}{{ end }}{{ end }}{{ if not (service "counting-service") }}http://localhost:9001{{ end }}';
console.log('Counting Service URL configured via Consul DNS:', window.COUNTING_SERVICE_URL);
EOH
        destination = "local/config.js"
        change_mode = "restart"
      }

      # Environment variables
      env {
        NGINX_PORT = "8080"
      }

      # Resource allocation
      resources {
        cpu    = 300  # MHz
        memory = 128  # MB
      }

      # Logging
      logs {
        max_files     = 5
        max_file_size = 10
      }
    }

    # Restart policy
    restart {
      attempts = 3
      delay    = "15s"
      interval = "5m"
      mode     = "fail"
    }

    # Update strategy
    update {
      max_parallel     = 1
      min_healthy_time = "10s"
      healthy_deadline = "3m"
      auto_revert      = true
    }
  }
}